export const RELATED_LINKS = [
  { label: "Mortgage Affordability Calculator",   href: "https://mortgageaffordabilityestimator.com" },
  { label: "Emergency Savings Calculator",         href: "https://emergencysavingscalculator.com" },
  { label: "Freelancer Rates Calculator",          href: "https://freelancerratescalculator.com" },
  { label: "Credit Card Debt Payoff Calculator",   href: "https://creditcarddebtpayoffcalculator.com" },
  { label: "Debt Reducing Calculator",             href: "https://debtreducingcalculator.com" },
  { label: "Side Hustle Tax Estimator",            href: "https://sidehustletaxestimator.com" },
  { label: "High Yield Savings Calculator",        href: "https://highyieldsavingscalculator.com" },
  { label: "Retirement Savings Gap",               href: "https://retirementsavingsgap.com" },
  { label: "Life Insurance Coverage Calculator",   href: "https://lifeinsurancecoveragecalculator.com" },
  { label: "Online Course ROI Calculator",         href: "https://onlinecourseroi.com" },
  { label: "Subscription Cost Calculator",         href: "https://mysubscriptioncost.com" },
  { label: "Email Attachment Size Checker",        href: "https://emailattachmentsize.com" },
  { label: "GPA Calculator",                       href: "https://gpacalculator.site" },
  { label: "YouTube Title Checker",                href: "https://youtubetitlechecker.com" },
  { label: "Strong Password Builder",              href: "https://strongpasswordbuilder.com" },
  { label: "Cool Username Generator",              href: "https://coolusernamegenerator.com" },
  { label: "MoneyWise Calculator Hub",             href: "https://moneywisecalculator.com" },
]

export const ALL_TOOLS = [
  {
    slug: "mortgage",
    href: "https://mortgageaffordabilityestimator.com",
    title: "Mortgage Affordability Calculator",
    description: "Find out how much home you can actually afford based on income, debts, and down payment.",
    icon: "🏠",
    color: "#b45309",
  },
  {
    slug: "emergency-savings",
    href: "https://emergencysavingscalculator.com",
    title: "Emergency Savings Calculator",
    description: "Calculate your target emergency fund and see exactly how long it will take to get there.",
    icon: "🛡️",
    color: "#166534",
  },
  {
    slug: "freelancer-rates",
    href: "https://freelancerratescalculator.com",
    title: "Freelancer Rates Calculator",
    description: "Set your freelance rate based on your income goal, expenses, taxes, and billable hours.",
    icon: "💼",
    color: "#0369a1",
  },
  {
    slug: "credit-card-payoff",
    href: "https://creditcarddebtpayoffcalculator.com",
    title: "Credit Card Debt Payoff Planner",
    description: "Map out your payoff timeline using snowball, avalanche, or emotional priority methods.",
    icon: "💳",
    color: "#b91c1c",
  },
  {
    slug: "debt-reducer",
    href: "https://debtreducingcalculator.com",
    title: "Debt Reducing Calculator",
    description: "See the true cost of your debt and how extra payments shrink your payoff timeline.",
    icon: "📉",
    color: "#7c3aed",
  },
  {
    slug: "side-hustle-tax",
    href: "https://sidehustletaxestimator.com",
    title: "Side Hustle Tax Estimator",
    description: "Estimate what you owe in self-employment and income tax on your side income.",
    icon: "🧾",
    color: "#c84b1f",
  },
  {
    slug: "high-yield-savings",
    href: "https://highyieldsavingscalculator.com",
    title: "High Yield Savings Calculator",
    description: "Project how your savings grow in a high-yield account with compound interest over time.",
    icon: "📈",
    color: "#0e7490",
  },
  {
    slug: "retirement-gap",
    href: "https://retirementsavingsgap.com",
    title: "Retirement Savings Gap",
    description: "Find out if you're on track for retirement and what it takes to close the gap.",
    icon: "🎯",
    color: "#7c3aed",
  },
  {
    slug: "life-insurance",
    href: "https://lifeinsurancecoveragecalculator.com",
    title: "Life Insurance Coverage Calculator",
    description: "Estimate the right amount of life insurance coverage using DIME, 10x, and other methods.",
    icon: "🔒",
    color: "#1a5ca8",
  },
  {
    slug: "course-roi",
    href: "https://onlinecourseroi.com",
    title: "Online Course ROI Calculator",
    description: "Calculate whether an online course or certification is worth the time and money.",
    icon: "🎓",
    color: "#166534",
  },
  {
    slug: "subscription-cost",
    href: "https://mysubscriptioncost.com",
    title: "Subscription Cost Calculator",
    description: "Add up all your subscriptions, audit what's worth keeping, and see the investment alternative.",
    icon: "📱",
    color: "#0e7490",
  },
  {
    slug: "email-attachment",
    href: "https://emailattachmentsize.com",
    title: "Email Attachment Size Checker",
    description: "Check if your file will send successfully across Gmail, Outlook, Yahoo, and iCloud Mail.",
    icon: "📎",
    color: "#1a5ca8",
  },
  {
    slug: "gpa",
    href: "https://gpacalculator.site",
    title: "GPA Calculator",
    description: "Calculate your cumulative GPA and find out what grades you need to hit your target.",
    icon: "📚",
    color: "#1d4ed8",
  },
  {
    slug: "youtube-title",
    href: "https://youtubetitlechecker.com",
    title: "YouTube Title Checker",
    description: "Score your YouTube title for length, keywords, structure, and click-through potential.",
    icon: "▶️",
    color: "#b91c1c",
  },
  {
    slug: "password-builder",
    href: "https://strongpasswordbuilder.com",
    title: "Strong Password Builder",
    description: "Generate cryptographically random passwords with customizable length and character sets.",
    icon: "🔑",
    color: "#2d6a4f",
  },
  {
    slug: "username-generator",
    href: "https://coolusernamegenerator.com",
    title: "Cool Username Generator",
    description: "Generate unique usernames in eight styles using keywords, word lists, and formatting patterns.",
    icon: "✨",
    color: "#7c3aed",
  },
]
